name: Build cross platform

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest]
    
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2

      - name: List all OS & Architectures supported by Go
        run: go tool dist list

      - name: Build
        run: bash ./build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: readme-updater
          path: build

  # publish:
  #   name: Publish for ${{ matrix.os }} - ${{ matrix.arch }}
  #   runs-on: ubuntu-latest
  #   uses: svenstaro/upload-release-action@v2
  #   strategy:
  #     matrix:
  #       include:
  #         - os: linux
  #           arch: amd64
  #         - os: linux
  #           arch: arm

  #         - os: windows
  #           arch: amd64
  #         - os: windows
  #           arch: arm

  #         - os: darwin
  #           arch: amd64
  #         - os: darwin
  #           arch: arm
    
